version: '3.8'

services:
  frontend:
    container_name: login_page_frontend
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
    - 3000:3000
    env_file:
      - ./.env