version: '3.8'

services:
  frontend:
    container_name: login_page_frontend
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - REACT_APP_ENVIRONMENT=development
      - REACT_APP_MAINTENANCE_MODE=false
    ports:
    - 3000:3000